[project]
name = "rmap"
version = "0.1.0"
description = "Scraping Reddit for shits and giggles"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.54.0",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
]
